export const storeData = {
    companyList: [
        { value: '', label: 'Please select a company' },
        { value: 'aci', label: 'Aci' },
        { value: 'acme', label: 'Acme' },
        { value: 'aristo', label: 'Aristo' },
        { value: 'becon', label: 'Becon' },
        { value: 'beximco', label: 'Beximco' },
        { value: 'diaper', label: 'Diaper & etc' },
        { value: 'drug', label: 'Drug' },
        { value: 'eyedrops', label: 'Eye Drops' },
        { value: 'foreign', label: 'Foreign' },
        { value: 'foodsupliment', label: 'food sup, cream, shampoo' },
        { value: 'general', label: 'General' },
        { value: 'healthcare', label: 'Healthcare' },
        { value: 'ibnsina', label: 'Ibn Sina' },
        { value: 'incepta', label: 'Incepta' },
        { value: 'injection', label: 'Injection' },
        { value: 'jmi', label: 'Jmi' },
        { value: 'nuvista', label: 'Nuvista' },
        { value: 'opsonin', label: 'Opsonin' },
        { value: 'orion', label: 'Orion' },
        { value: 'pacifiq', label: 'Pacifiq' },
        { value: 'popular', label: 'Popular' },
        { value: 'radiant', label: 'Radiant' },
        { value: 'reneta', label: 'Reneta' },
        { value: 'sanofi', label: 'Sanofi' },
        { value: 'sample', label: 'Sample' },
        { value: 'skf', label: 'Skf' },
        { value: 'square', label: 'Square' },
        { value: 'surgical', label: 'Surgical' },
        { value: 'sun', label: 'Sun' },
        { value: 'unihealth', label: 'Uni Health' },
        { value: 'whitehorse', label: 'White Horse' },
        { value: 'ziska', label: 'Ziska' },
        { value: 'others', label: 'All Others' }
    ],
    stockCompanyList: [
        { value: '', label: 'Please select a company' },
        { value: 'aci', label: 'Aci' },
        { value: 'acme', label: 'Acme' },
        { value: 'aristo', label: 'Aristo' },
        { value: 'beximco', label: 'Beximco' },
        { value: 'drug', label: 'Drug' },
        { value: 'healthcare', label: 'Healthcare' },
        { value: 'incepta', label: 'Incepta' },
        { value: 'opsonin', label: 'Opsonin' },
        { value: 'reneta', label: 'Reneta' },
        { value: 'square', label: 'Square' },
        { value: 'unihealth', label: 'Uni Health' },
        { value: 'others', label: 'All Others' },
        { value: 'rashu', label: 'Rashu`s Product' },
    ],
    productType: [
        { value: '', label: 'Please select a Type' },
        { value: 'product', label: 'Short Product' },
        { value: 'stock', label: 'Stock Product' },
    ]

}
